require:
  - rubocop-faker
  - rubocop-ordered_methods
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.7.0

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Exclude:
    - Guardfile
    - config/initializers/backtrace_silencers.rb
  Max: 100

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - 'spec/**/*spec.rb'

Metrics/MethodLength:
  Max: 20

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Exclude:

Rails/SkipsModelValidations:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
